### ISSUE TITLE
OnError not Working 

### ISSUE THREAD

**Issue by avinlakhera** [alexjoffroy/react-fitted-image#10]
It seems the onError functionality is not working . I was implementing the functionality where if Image is not found then it should show the default Image but onError is not working . below is my sample code 

    test() {
        alert("Error occured")
    }

render () {
<FittedImage
                            fit="cover"
                            src={object.imageurl}
                            onError={this.test}
                            className="dj-online-profile-image module"
                        />
}

any suggestion on this one is I am doing anything wrong here

**Comment by alexjoffroy** [comment]
Do you have something like

```js
<FittedImage
  onError={this.test}
  ... />
```

in your render method ?

**Comment by avinlakhera** [comment]
yes

**Comment by avinlakhera** [comment]
I want to implement a functionality where if image is not available we can show some place holder

**Comment by alexjoffroy** [comment]
I just checked on my workspace with the example from the sources and it's working fine. Here's my code:

```js
import React from 'react';
import { render } from 'react-dom';
import FittedImage from '../../lib/react-fitted-image.js';

const fitOptions = [
  { value: 'auto', label: 'Auto' },
  { value: 'contain', label: 'Contain' },
  { value: 'cover', label: 'Cover' }
];
const sizeOptions = [
  { value: '1200/700', label: '1200x700' },
  { value: '500/800', label: '500x800' },
  { value: '900/900', label: '900x900' }
];

const App = React.createClass({

  getInitialState() {
    return {
      fit: 'contain',
      size: '1200/700'
    };
  },

  getFitOptions() {
    return fitOptions.map( (opt, key) => {
      return <option value={opt.value} key={key}>{opt.label}</option>;
    });
  },

  getSizeOptions() {
    return sizeOptions.map( (opt, key) => {
      return <option value={opt.value} key={key}>{opt.label}</option>;
    });
  },

  onPropChange(prop, e)  {
    let state = {};
    state[prop] = e.target.value;
    this.setState(state);
  },

  onError() {
    alert('Error !');
  },

  render() {
    return (
      <div className="App">
          <div className="Settings">
            <label>Fit property</label>
            <select value={this.state.fit} onChange={this.onPropChange.bind(this, 'fit')}>
              {this.getFitOptions()}
            </select>
          </div>
          <div className="Settings">
            <label>Image size</label>
            <select value={this.state.size} onChange={this.onPropChange.bind(this, 'size')}>
              {this.getSizeOptions()}
            </select>
          </div>
        <div className="Wrapper">
          <FittedImage
            background
            fit={this.state.fit}
            src={'https://placeimg.com/'+this.state.size+'/animals'}
            onError={this.onError}
            loader={<div className="Loader">Loading...</div>} />
        </div>
      </div>
    );
  }

})

render(<App />, document.getElementById('app'));

```

If you still get the problem, can you put an example with the bug somewhere ?

**Comment by avinlakhera** [comment]
This is my sample code and it seems onError is not working 

constructor() {
        super();
        this.onError = this.onError.bind(this)
    }

onError() {
        alert("hello");
    }

render() {
        return (
            <div>
                {this.props.djList.map((object, i) => {
                    return (<div>
                        <FittedImage
                            fit="cover"
                            src={object.imageurl}
                            onError={this.onError}
                            />
                        </div>)
                })}

            </div>
        )
    }

**Comment by alexjoffroy** [comment]
What is the point of `this.onError = this.onError.bind(this)` ? I am not sure you can override this.onError like this.

**Comment by Shubham0850** [comment]
`<img
            src={require(`../../../../server/productImg/${imageSrc}`)}
            alt="product-image"
            onError={(e) => {
              alert("error")
              console.log(e.target.src);
              e.target.onerror = null
              e.target.src = './images/image-not-available.png';
            }}
          />`

**Comment by Shubham0850** [comment]
onError is not firing when product image is not found????
