### ISSUE TITLE
Integrate object-fit-images

### ISSUE THREAD

**Issue by bfred-it** [alexjoffroy/react-fitted-image#3]
Would it make sense to base react-fitted-image on [object-fit-images](https://github.com/bfred-it/object-fit-images) to improve its performance and support?

**Comment by alexjoffroy** [comment]
Hi @bfred-it, thanks for the interest. Currently, I'm not sure if it makes sense but I think it deserves a try. Let me check asap.

**Comment by alexjoffroy** [comment]
Currently, it seems it does not really makes sense, so  I close the issue. If someone need id let me know.
