### ISSUE TITLE
React peerDependency version bump

### ISSUE THREAD

**Issue by jasonblanchard** [alexjoffroy/react-fitted-image#5]
Is this project still being maintained? Looks like the [react peer dependency in package.json](https://github.com/alexjoffroy/react-fitted-image/blob/master/package.json#L52) needs a version bump.

**Comment by alexjoffroy** [comment]
@jasonblanchard As I'm not on React stuff right now, I did not update the library since a long time... But feel free to submit a PR. Or I will do it ASAP.

**Comment by alexjoffroy** [comment]
React peerDependency updated to 15.4.x, thanks to @jakehamilton.

I think the devDependencies should also be updated (not only React), I'll do it in the next release.
