### ISSUE TITLE
Image load and error events does not fire when using fallback

### ISSUE THREAD

**Issue by jakehamilton** [alexjoffroy/react-fitted-image#6]
The `onLoad` and `onError` events should fire when the given image finishes loading. Currently, this is not the case when `object-fit` is not supported and we use the fallback.

To reproduce:

1. Use a fitted image component and assign an `onLoad` prop

```js
const log = (...args) => console.log(...args)
const App = _ => <FittedImage onLoad={log} onError={log} src="my-image.jpg" fit="cover" />

ReactDOM.render(<App />, document.querySelector('#app'))
```

2. Open your application in a browser that does not support `object-fit` (ex. IE 11).

3. View the result, the events do not fire.

**Comment by alexjoffroy** [comment]
It sounds like a nice improvement. It seems you started to work on a PR, so let me hear about it when you're done ! Thanks.

**Comment by alexjoffroy** [comment]
PR merged. Thanks, it will be included in the next release in a few days :)
